# fly.toml app configuration file generated for employee-management-portal on 2023-09-26T16:21:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "employee-management-portal"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
